image: golang:latest

stages:
  - test
  - build

test:
  stage: test
  script:
    - set +e
    - go test ./...
    - go run main.go -generate-config
    - ln -s $PWD/Rename_to_.repos.yml ~/.repos.yml
    - go run main.go || true

build:
  stage: build
  script:
    - go version
    - GOOS=darwin GOARCH=amd64 go build -o repos-$GOOS-$GOARCH
    - GOOS=darwin GOARCH=arm64 go build -o repos-$GOOS-$GOARCH
    - GOOS=linux  GOARCH=amd64 go build -o repos-$GOOS-$GOARCH
    - GOOS=linux  GOARCH=arm64 go build -o repos-$GOOS-$GOARCH
  artifacts:
    untracked: true