image: golang:latest

stages:
  - build

before_script:
  - apt-get update --yes
  - apt-get install --yes python3 cmake pandoc

build:
  stage: build
  script:
    - export PATH=$HOME/.local/bin:$PATH
    - go version
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_INSTALL_PREFIX=${CI_PROJECT_DIR}/install
    - cd ../src
    - export GOOS=darwin   GOARCH=amd64 ; go build -o ${CI_PROJECT_DIR}/install/repos-${GOOS}-${GOARCH}
    - export GOOS=darwin   GOARCH=arm64 ; go build -o ${CI_PROJECT_DIR}/install/repos-${GOOS}-${GOARCH}
    - export GOOS=linux    GOARCH=amd64 ; go build -o ${CI_PROJECT_DIR}/install/repos-${GOOS}-${GOARCH}
    - export GOOS=linux    GOARCH=arm64 ; go build -o ${CI_PROJECT_DIR}/install/repos-${GOOS}-${GOARCH}
    - export GOOS=windows  GOARCH=amd64 ; go build -o ${CI_PROJECT_DIR}/install/repos-${GOOS}-${GOARCH}
  artifacts:
    paths:
      - install
