image: golang:latest

stages:
  - build
  - release

build:
  stage: build
  script:
    - apt-get update --yes
    - apt-get install --yes python3 cmake pandoc
    - export PATH=$HOME/.local/bin:$PATH
    - go version
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_INSTALL_PREFIX=${CI_PROJECT_DIR}/install
    - cd ../src
    - export GOOS=darwin   GOARCH=amd64 ; go build -o ${CI_PROJECT_DIR}/install/repos-${GOOS}-${GOARCH}
    - export GOOS=darwin   GOARCH=arm64 ; go build -o ${CI_PROJECT_DIR}/install/repos-${GOOS}-${GOARCH}
    - export GOOS=linux    GOARCH=amd64 ; go build -o ${CI_PROJECT_DIR}/install/repos-${GOOS}-${GOARCH}
    - export GOOS=linux    GOARCH=arm64 ; go build -o ${CI_PROJECT_DIR}/install/repos-${GOOS}-${GOARCH}
    - export GOOS=windows  GOARCH=amd64 ; go build -o ${CI_PROJECT_DIR}/install/repos-${GOOS}-${GOARCH}
  artifacts:
    paths:
      - install

release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG                 # Run this job when a tag is created
  script:
    - echo "running release_job"
  release:                               # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    tag_name: '$CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG'
