.TH "rcd" "1" 

.SH "NAME"
.PP
rcd is a shell function that changes directory to the path of the named repo
from \fC$HOME/.config/repos.yml\fP.

.SH "SYNOPSIS"
.RS
.nf
\fCrcd REPO
\fP
.fi
.RE

.PP
Change to the path associated to \fCREPO\fP in \fC$HOME/.config/repos.yml\fP.  This
function has autocompletion.

.PP
See \fCman (1) repos\fP for more information about the \fCrepos\fP command and the
\fCrepos.yml\fP configuration file.

.SH "BUGS"
.PP
The accompanying script \fIrepos_completion.bash\fP defines autocomplete and the
\fCrcd\fP that takes a repo name.  It uses the \fCrepos\fP executable.  If there is no
\fC$HOME/.config/repos.yml\fP, the \fCrcd\fP shell function will not work.

.SH "AUTHOR"
.PP
Philippe Carphin
.SH "COPYRIGHT"
.PP
Philippe Carphin
