[package]
name = "repos-add"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "1.0.4"
serde_yaml = "0.8.24"
serde = { version = "1", features = ["derive"] }
