#
# This file was generated by autocomplete-generator https://gitlab.com/philippecaphin/autocomplete-generator
#

# This is the function that will be called when we press TAB.
#
# Its purpose is # to examine the current command line (as represented by the
# array COMP_WORDS) and to determine what the autocomplete should reply through
# the array COMPREPLY.
#
# This function is organized with subroutines who  are responsible for setting
# the 'candidates' variable.
#
# The compgen then filters out the candidates that don't begin with the word we are
# completing. In this case, if '--' is one of the words, we set empty candidates,
# otherwise, we look at the previous word and delegate # to candidate-setting functions
__complete_repos() {

	COMPREPLY=()

	# We use the current word to filter out suggestions
	local cur="${COMP_WORDS[COMP_CWORD]}"

	# Compgen: takes the list of candidates and selects those matching ${cur}.
	# Once COMPREPLY is set, the shell does the rest.
	COMPREPLY=( $(compgen -W "$(__suggest_repos_candidates)" -- ${cur}))

	return 0
}

__suggest_repos_candidates(){
	# We use the current word to decide what to do
	local cur="${COMP_WORDS[COMP_CWORD]}"
	if __repos_dash_dash_in_words ; then
		return
	fi

	option=$(__repos_get_current_option)
	if [[ "$option" != "" ]] ; then
		__suggest_repos_args_for_option ${option}
	else
		if [[ "$cur" = -* ]] ; then
			__suggest_repos_options
		fi
	fi

	echo "$candidates"
}

__repos_dash_dash_in_words(){
	for ((i=0;i<COMP_CWORD-1;i++)) ; do
		w=${COMP_WORD[$i]}
		if [[ "$w" == "--" ]] ; then
			return 0
		fi
	done
	return 1
}

__repos_get_current_option(){
	# The word before that
	local prev="${COMP_WORDS[COMP_CWORD-1]}"
	if [[ "$prev" == -* ]] ; then
		echo "$prev"
	fi
}

__suggest_repos_options(){
	candidates=" Usage -generate-config -j -list-names -list-repos -no-fetch -path -r"
}

__suggest_repos_args_for_option(){
	case "$1" in
		-generate-config) __suggest_repos_key_generate_config_values ;;
		-j) __suggest_repos_key_j_values ;;
		-list-names) __suggest_repos_key_list_names_values ;;
		-list-repos) __suggest_repos_key_list_repos_values ;;
		-no-fetch) __suggest_repos_key_no_fetch_values ;;
		-path) __suggest_repos_key_path_values ;;
		-r) __suggest_repos_key_r_values ;;
	esac
}

__suggest_repos_key_generate_config_values(){
	candidates=""
}

__suggest_repos_key_j_values(){
	candidates=""
}

__suggest_repos_key_list_names_values(){
	candidates=""
}

__suggest_repos_key_list_repos_values(){
	candidates=""
}

__suggest_repos_key_no_fetch_values(){
	candidates=""
}

__suggest_repos_key_path_values(){
	candidates=""
}

__suggest_repos_key_r_values(){
    candidates="$(repos -list-names)"
}

complete -o default -F __complete_repos repos

function rcd(){
    local dir=$(repos -get-dir $1)
    echo "[33mcd $dir[0m"
    cd $dir
}

__complete_rcd(){
	COMPREPLY=()
	# We use the current word to filter out suggestions
	local cur="${COMP_WORDS[COMP_CWORD]}"
	# Compgen: takes the list of candidates and selects those matching ${cur}.
	# Once COMPREPLY is set, the shell does the rest.
	COMPREPLY=( $(compgen -W "$(repos -list-names)" -- ${cur}))
}
complete -o default -F __complete_rcd rcd
