#+TITLE: Repos
* NAME
repos is a command line tool keep track of local git repos.
* SYNOPSIS

#+begin_src shell
repos [-no-fetch] [-j NJOBS]
repos -generate-config >> ~/.config/repos.yml
repos -get-dir REPO
#+end_src

Without arguments report with info for git repos listed in ~$HOME/.config/repos.yml~.
See section CONFIGURATION for details on this ~repos.yml~ file.

#+begin_src shell
rcd NAME
#+end_src

~cd~ to the path of a repo by giving its name with autocompletion of repo names.

See OPTIONS section for more options for ~repos~.

* DESCRIPTION
Without any arguments, the ~repos~ looks in ~$HOME/.config/repos.yml~ and prints
a report of on various information about the git repo:
- Remote state: up-to-date, behind, ahead, diverged (relative to the currently
  checked out branch in the repo).
- Status: Presence of staged or unstaged chages, presence of untracked files.
- Time since last commit: The time in hours since the last commit was made on
  the currently checked out branch.  This number does not indicate anything in and
  of itself.
  
See section OPTIONS for more available options for ~repos~.

* CONFIGURATION

The ~$HOME/.config/repos.yml~ file should look like

#+begin_src yaml
repos:
  a-repo:
    path: "/path/to/a-repo"
  b-repo:
    path: "/path/to/b-repo"
#+end_src

If the ~-generate-config~ is passed, instead of printing the report, ~repos~
will look for git repositories in ~$PWD~ and print on STDOUT the contents of the
corresponding ~$HOME/.config/repos.yml~ file.

#+begin_src yaml
cd ${somewhere}
repos -generate-config > ~/.config/repos.yml
cd ${somewhere_else}
repos -generate-config >> ~/.config/repos.yml
#+end_src

The config file is meant to prioritize ease of editing by humans.  Rather than
managing the config file fully automatically, we give the human pieces that they
can use to manage their config file.

* OPTIONS

** ~-generate-config~

Looks in ~$PWD~ for git repositories and outputs the content of a ~repos.yml~
file ~STDOUT~.

** ~-no-fetch~

Skips the fetching step.

** ~-j NJOBS~

Use up to ~NJOBS~ concurrent processes to assess the status of the git
repositories.

** ~-recent~

Run ~git recent~ in all repositories.  Showing commits made *today* and
*yesterday*.  This is very useful if you work on many repos and want to get a
condensed report of recent activity.

** ~-days~

Only useful with the ~-recent~ flag.  Go more than one day before yesterday in
the commit history.

* BUGS
The accompanying script =repos_completion.bash= defines autocomplete and the
~rcd~ that takes a repo name.  It uses the ~repos~ executable.  If there is no
~$HOME/.config/repos.yml~, the ~rcd~ shell function will not work.

* AUTHOR
Philippe Carphin
* COPYRIGHT
Philippe Carphin
